=== bozonhiggsa/JavaCoreInAction/input2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="TouristVouchers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="TouristVoucher" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="TouristVoucher">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="TypeVoucher" type="xsd:string"/>
                <xsd:element name="Country" type="xsd:string"/>
                <xsd:element name="NumberDaysNights" type="xsd:int"/>
                <xsd:element ref="Transport" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="HotelCharacteristics"/>
                <xsd:element ref="Cost"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="KindOfTransport">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="bus" />
            <xsd:enumeration value="plane" />
            <xsd:enumeration value="boat" />
            <xsd:enumeration value="train" />
            <xsd:enumeration value="taxi" />
            <xsd:enumeration value="car" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:attribute name="voucher_include">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="voucher" />
                <xsd:enumeration value="include" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:attribute>

    <xsd:element name="Transport">
            <xsd:complexType>
                <xsd:simpleContent>
                    <xsd:extension base="KindOfTransport">
                        <xsd:attribute ref="voucher_include" use="required"/>
                    </xsd:extension>
                </xsd:simpleContent>
            </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="KindOfFood">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([A-Z]{2})[A-Z|\\+]?"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:attribute name="hotel_include">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="hotel" />
                <xsd:enumeration value="include" />
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:attribute>

    <xsd:element name="Food">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="KindOfFood">
                    <xsd:attribute ref="hotel_include" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:simpleType name="KindOfApartments">
        <xsd:restriction base="xsd:int">
            <xsd:enumeration value="1" />
            <xsd:enumeration value="2" />
            <xsd:enumeration value="3" />
            <xsd:enumeration value="4" />
            <xsd:enumeration value="5" />
            <xsd:enumeration value="6" />
            <xsd:enumeration value="7" />
            <xsd:enumeration value="8" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="Apartments">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="KindOfApartments">
                    <xsd:attribute ref="hotel_include" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="TV">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute ref="hotel_include" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Conditioner">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute ref="hotel_include" use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>



    <xsd:element name="HotelCharacteristics">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Stars">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:int">
                            <xsd:enumeration value="1" />
                            <xsd:enumeration value="2" />
                            <xsd:enumeration value="3" />
                            <xsd:enumeration value="4" />
                            <xsd:enumeration value="5" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element ref="Food" minOccurs="0" maxOccurs="10"/>
                <xsd:element ref="TV" minOccurs="0" maxOccurs="10"/>
                <xsd:element ref="Conditioner" minOccurs="0" maxOccurs="10"/>
                <xsd:element ref="Apartments" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Cost">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Money">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:double">
                            <xsd:minInclusive value="0" />
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element ref="Include"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Include">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Transport" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="TV" minOccurs="0" maxOccurs="10"/>
                <xsd:element ref="Conditioner" minOccurs="0" maxOccurs="10"/>
                <xsd:element ref="Apartments" maxOccurs="unbounded"/>
                <xsd:element ref="Food" minOccurs="0" maxOccurs="10"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== bozonhiggsa/JavaCoreInAction/input2.xml
<?xml version="1.0" encoding="UTF-8"?>
<TouristVouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="input2.xsd">
    <TouristVoucher>
        <TypeVoucher>Leisure</TypeVoucher>
        <Country>Italy</Country>
        <NumberDaysNights>14</NumberDaysNights>
        <Transport voucher_include="voucher">plane</Transport>
        <Transport voucher_include="voucher">bus</Transport>
        <Transport voucher_include="voucher">taxi</Transport>
        <Transport voucher_include="voucher">train</Transport>
        <HotelCharacteristics>
            <Stars>3</Stars>
            <Food hotel_include="hotel">RO</Food>
            <Food hotel_include="hotel">BB</Food>
            <Food hotel_include="hotel">HB</Food>
            <Food hotel_include="hotel">HB+</Food>
            <Food hotel_include="hotel">FB</Food>
            <Food hotel_include="hotel">FB+</Food>
            <TV hotel_include="hotel">21 inches</TV>
            <TV hotel_include="hotel">27 inches</TV>
            <Conditioner hotel_include="hotel">Aux</Conditioner>
            <Conditioner hotel_include="hotel">Hitachi</Conditioner>
            <Conditioner hotel_include="hotel">Fuji</Conditioner>
            <Apartments hotel_include="hotel">1</Apartments>
            <Apartments hotel_include="hotel">2</Apartments>
            <Apartments hotel_include="hotel">3</Apartments>
        </HotelCharacteristics>
        <Cost>
            <Money>500</Money>
            <Include>
                <Transport voucher_include="include">plane</Transport>
                <Transport voucher_include="include">taxi</Transport>
                <TV hotel_include="include">21 inches</TV>
                <Apartments hotel_include="include">2</Apartments>
                <Food hotel_include="include">BB</Food>
            </Include>
        </Cost>
    </TouristVoucher>

    <TouristVoucher>
        <TypeVoucher>Business Trip</TypeVoucher>
        <Country>England</Country>
        <NumberDaysNights>7</NumberDaysNights>
        <Transport voucher_include="voucher">plane</Transport>
        <Transport voucher_include="voucher">bus</Transport>
        <Transport voucher_include="voucher">car</Transport>
        <Transport voucher_include="voucher">boat</Transport>
        <Transport voucher_include="voucher">train</Transport>
        <HotelCharacteristics>
            <Stars>4</Stars>
            <Food hotel_include="hotel">HB</Food>
            <Food hotel_include="hotel">HB+</Food>
            <Food hotel_include="hotel">FB</Food>
            <Food hotel_include="hotel">FB+</Food>
            <Food hotel_include="hotel">AI</Food>
            <TV hotel_include="hotel">21 inches</TV>
            <TV hotel_include="hotel">27 inches</TV>
            <TV hotel_include="hotel">33 inches</TV>
            <Conditioner hotel_include="hotel">Aux</Conditioner>
            <Conditioner hotel_include="hotel">Fuji</Conditioner>
            <Apartments hotel_include="hotel">1</Apartments>
            <Apartments hotel_include="hotel">2</Apartments>
            <Apartments hotel_include="hotel">3</Apartments>
            <Apartments hotel_include="hotel">4</Apartments>
        </HotelCharacteristics>
        <Cost>
            <Money>900</Money>
            <Include>
                <Transport voucher_include="include">train</Transport>
                <Transport voucher_include="include">bus</Transport>
                <TV hotel_include="include">21 inches</TV>
                <Conditioner hotel_include="include">Aux</Conditioner>
                <Apartments hotel_include="include">3</Apartments>
                <Food hotel_include="include">HB+</Food>
            </Include>
        </Cost>
    </TouristVoucher>

    <TouristVoucher>
        <TypeVoucher>Travelling</TypeVoucher>
        <Country>Spain</Country>
        <NumberDaysNights>21</NumberDaysNights>
        <Transport voucher_include="voucher">plane</Transport>
        <Transport voucher_include="voucher">bus</Transport>
        <Transport voucher_include="voucher">taxi</Transport>
        <HotelCharacteristics>
            <Stars>5</Stars>
            <Food hotel_include="hotel">HB</Food>
            <Food hotel_include="hotel">HB+</Food>
            <Food hotel_include="hotel">FB</Food>
            <Food hotel_include="hotel">FB+</Food>
            <Food hotel_include="hotel">AI</Food>
            <Food hotel_include="hotel">AIP</Food>
            <Food hotel_include="hotel">UAI</Food>
            <TV hotel_include="hotel">21 inches</TV>
            <TV hotel_include="hotel">27 inches</TV>
            <TV hotel_include="hotel">33 inches</TV>
            <Conditioner hotel_include="hotel">Aux</Conditioner>
            <Conditioner hotel_include="hotel">Fuji</Conditioner>
            <Apartments hotel_include="hotel">1</Apartments>
            <Apartments hotel_include="hotel">2</Apartments>
            <Apartments hotel_include="hotel">3</Apartments>
            <Apartments hotel_include="hotel">4</Apartments>
            <Apartments hotel_include="hotel">5</Apartments>
        </HotelCharacteristics>
        <Cost>
            <Money>1200</Money>
            <Include>
                <Transport voucher_include="include">boat</Transport>
                <Transport voucher_include="include">bus</Transport>
                <TV hotel_include="include">27 inches</TV>
                <Conditioner hotel_include="include">Fuji</Conditioner>
                <Apartments hotel_include="include">4</Apartments>
                <Food hotel_include="include">AI</Food>
            </Include>
        </Cost>
    </TouristVoucher>

</TouristVouchers>
